/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.management;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AddFlight extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddFlight
     */
    public AddFlight() {
        initComponents();
        jButton1.setBackground(Color.CYAN);
        jButton2.setBackground(Color.CYAN);
        this.setSize(900, 700);
        autoId();
    }
    
    Connection con;
    PreparedStatement pre;
    
    public void autoId()
    {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddFlight.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdatabase", "root", "Muskaan@010799");
            } catch (SQLException ex) {
                Logger.getLogger(AddFlight.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                java.sql.Statement s = con.createStatement();
                ResultSet rs = s.executeQuery("Select MAX(FlightID)from flight");
            rs.next();
            if(rs.getString("MAX(FlightID)")== null)
            {
                FlightID.setText("FS001");
            }
            else
            {
                long id = Long.parseLong(rs.getString("MAX(FlightID)").substring(2, rs.getString("MAX(FlightID)").length()));
                id++;
                FlightID.setText("FS"+String.format("%03d", id));
            }
            } catch (SQLException ex) {
                Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FlightID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        flightName = new javax.swing.JTextField();
        arrival = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        departure = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateTravel = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        seatLeft = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fare = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        timeTravel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ozzie Black", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Flight Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 28, 263, -1));

        FlightID.setEditable(false);
        FlightID.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        FlightID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightIDActionPerformed(evt);
            }
        });
        getContentPane().add(FlightID, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 26, 197, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Flight Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 171, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Arrival");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 226, -1, -1));

        flightName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(flightName, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 168, 100, -1));

        arrival.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(arrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 223, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Departure");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 288, -1, -1));

        departure.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        departure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureActionPerformed(evt);
            }
        });
        getContentPane().add(departure, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 285, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 351, -1, -1));
        getContentPane().add(dateTravel, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 351, 136, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("No. Seats Left");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 171, -1, -1));

        seatLeft.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        seatLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatLeftActionPerformed(evt);
            }
        });
        getContentPane().add(seatLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 168, 104, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Fare Per Person");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 226, -1, -1));

        fare.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(fare, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 223, 104, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Time of Travel");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 287, -1, -1));

        timeTravel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(timeTravel, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 284, 104, -1));

        jButton1.setFont(new java.awt.Font("Ozzie Black", 3, 24)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 495, 123, 62));

        jButton2.setFont(new java.awt.Font("Ozzie Black", 3, 24)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 495, 125, 62));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/management/add_flight.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String FlightId = FlightID.getText();
        String FlightName = flightName.getText();
        String Arrival = arrival.getText();
        String Departure = departure.getText();
        String Seats = seatLeft.getText();
        String Fare = fare.getText();
        
        DateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        String date = dt.format(dateTravel.getDate());
        
        String duration = timeTravel.getText();
        
        try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdatabase", "root", "Muskaan@010799");
                
                pre = con.prepareStatement("insert into flight(FlightId, FlightName, Arrival,Departure, Seats, Fare, Date, Duration)values(?,?,?,?,?,?,?,?)");
                pre.setString(1, FlightId);
                pre.setString(2, FlightName);
                pre.setString(3, Arrival);
                pre.setString(4, Departure);
                pre.setString(5, Seats);
                pre.setString(6, Fare);
                pre.setString(7, date);
                pre.setString(8, duration);
                
                pre.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Flight Added");
            } catch (SQLException ex) {
                Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void FlightIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlightIDActionPerformed

    private void departureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureActionPerformed

    private void seatLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatLeftActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FlightID;
    private javax.swing.JTextField arrival;
    private com.toedter.calendar.JDateChooser dateTravel;
    private javax.swing.JTextField departure;
    private javax.swing.JTextField fare;
    private javax.swing.JTextField flightName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField seatLeft;
    private javax.swing.JTextField timeTravel;
    // End of variables declaration//GEN-END:variables
}
