/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airline.management;
import java.awt.Color;
import com.mysql.cj.xdevapi.Result;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Book_Ticket extends javax.swing.JInternalFrame {

    /**
     * Creates new form Book_Ticket
     */
    public Book_Ticket() {
        initComponents();
        jButton3.setBackground(Color.BLUE);
        jButton5.setBackground(Color.BLUE);
        this.setSize(900, 700);
        autoId();
    }
    
    public void autoId()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdatabase", "root", "Muskaan@010799");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("Select MAX(TicketId)from bookticket");
            rs.next();
            if(rs.getString("MAX(TicketId)")== null)
            {
                TicketID.setText("TK001");
            }
            else
            {
                long id = Long.parseLong(rs.getString("MAX(TicketId)").substring(2, rs.getString("MAX(TicketId)").length()));
                id++;
                TicketID.setText("TK"+String.format("%03d", id));
            }
        }
        catch(ClassNotFoundException | SQLException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        arrival = new javax.swing.JComboBox<>();
        departure = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TicketID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CustId = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Fare = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        NoOfTickets = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        TotalFare = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ozzie Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Book Ticket");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Arrival");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 42, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Departure");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 42, -1, -1));

        arrival.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        arrival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ahmedabad", "Bangalore", "Bhopal", "Chennai", "Chandigarh", "Delhi", "Goa", "Hyderabad", "Indore", "Jabalpur", "Kolkata", "Mumbai", "Nagpur", "Pune", "Ranchi" }));
        arrival.setSelectedIndex(-1);
        jPanel1.add(arrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 89, -1, -1));

        departure.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        departure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ahmedabad", "Bangalore", "Bhopal", "Chennai", "Chandigarh", "Delhi", "Goa", "Hyderabad", "Indore", "Jabalpur", "Kolkata", "Mumbai", "Nagpur", "Pune", "Ranchi" }));
        departure.setSelectedIndex(-1);
        departure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureActionPerformed(evt);
            }
        });
        jPanel1.add(departure, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 89, -1, -1));

        jButton1.setFont(new java.awt.Font("Ozzie Black", 3, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 142, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/management/arrival.jpg"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 200));

        jTable1.setBackground(new java.awt.Color(255, 255, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight ID", "Flight Name", "Arrival", "Departure", "Date"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 273, 478, 370));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Ticket ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        TicketID.setEditable(false);
        TicketID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        getContentPane().add(TicketID, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 92, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Customer ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, -1, 20));

        CustId.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        CustId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustIdActionPerformed(evt);
            }
        });
        getContentPane().add(CustId, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 108, -1));

        jButton2.setFont(new java.awt.Font("Ozzie Black", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("First Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Last Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Contact");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Gender");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 110, -1));
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 110, -1));
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 110, -1));
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 110, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Fare");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        Fare.setEditable(false);
        Fare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FareActionPerformed(evt);
            }
        });
        getContentPane().add(Fare, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 81, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("No. of Tickets");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, -1, -1));

        NoOfTickets.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NoOfTicketsStateChanged(evt);
            }
        });
        getContentPane().add(NoOfTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 81, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Total Fare");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, -1, -1));

        TotalFare.setEditable(false);
        TotalFare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalFareActionPerformed(evt);
            }
        });
        getContentPane().add(TotalFare, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 81, -1));

        jButton3.setFont(new java.awt.Font("Ozzie Black", 3, 18)); // NOI18N
        jButton3.setText("Book");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 580, 120, 50));

        jButton5.setFont(new java.awt.Font("Ozzie Black", 3, 18)); // NOI18N
        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 580, 120, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline/management/book_tickets.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void departureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departureActionPerformed

    private void CustIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustIdActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        this.hide();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try {
            // TODO add your handling code here:
            Connection con;
            PreparedStatement pre;
            
            int cc;
            String Arrival = arrival.getSelectedItem().toString();
            String Departure = departure.getSelectedItem().toString();
            
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdatabase", "root", "Muskaan@010799");
            java.sql.Statement s = con.createStatement();
            
            ResultSet rs = s.executeQuery("select FlightId, FlightName, Arrival, Departure, Date from flight where Arrival='"+Arrival+"' && Departure='"+Departure+"'");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "No flight available");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Book_Ticket.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Book_Ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        try
        {
            int column = 0;
            int row = jTable1.getSelectedRow();
            String value = jTable1.getModel().getValueAt(row, column).toString();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdatabase", "root", "Muskaan@010799");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from flight where FlightId = '"+value+"'");
            rs.next();
            Fare.setText(rs.getString("Fare"));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void TotalFareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalFareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalFareActionPerformed

    private void NoOfTicketsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NoOfTicketsStateChanged
        // TODO add your handling code here:
        int count = (Integer)NoOfTickets.getValue();
        int fare = Integer.valueOf(Fare.getText());
        TotalFare.setText(String.valueOf(fare*count));
    }//GEN-LAST:event_NoOfTicketsStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdatabase", "root", "Muskaan@010799");
            Statement st = con.createStatement();
            String CustomerId = CustId.getText();
            ResultSet rs = st.executeQuery("select * from customers where CustomerId = '"+CustomerId+"'");
            if(rs.next()){
                fname.setText(rs.getString("FirstName"));
                lname.setText(rs.getString("LastName"));
                contact.setText(rs.getString("Contact"));
                gender.setText(rs.getString("Gender"));
            }
            else{
                JOptionPane.showMessageDialog(null, "Customer Not Found");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String ticketid = TicketID.getText();
        String customerid = CustId.getText();
        String firstname = fname.getText();
        String lastname = lname.getText();
        String Contact = contact.getText();
        String Gender = gender.getText();
        String fare = Fare.getText();
        String tickets = NoOfTickets.getValue().toString();
        String totalfare = TotalFare.getText();
        try
        {
            int column = 0;
            int row = jTable1.getSelectedRow();
            String value = jTable1.getModel().getValueAt(row, column).toString();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdatabase", "root", "Muskaan@010799");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from flight where FlightId = '"+value+"'");
            rs.next();
            String flightid = rs.getString("FlightId");
            String flightname = rs.getString("FlightName");
            String arrival = rs.getString("Arrival");
            String departure = rs.getString("Departure");
            String date = rs.getString("Date");
            if(!firstname.isEmpty()&& !totalfare.isEmpty()){
                st.executeUpdate("insert into bookticket values('"+ticketid+"','"+flightid+"','"+flightname+"','"+arrival+"','"+departure+"','"+date+"','"+customerid+"','"+firstname+"','"+lastname+"','"+Contact+"','"+Gender+"', '"+fare+"','"+tickets+"','"+totalfare+"')");
                JOptionPane.showMessageDialog(null, "Ticket booked successfully");
            }
            else{
                JOptionPane.showMessageDialog(null, "Please enter correct details");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void FareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FareActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustId;
    private javax.swing.JTextField Fare;
    private javax.swing.JSpinner NoOfTickets;
    private javax.swing.JTextField TicketID;
    private javax.swing.JTextField TotalFare;
    private javax.swing.JComboBox<String> arrival;
    private javax.swing.JTextField contact;
    private javax.swing.JComboBox<String> departure;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lname;
    // End of variables declaration//GEN-END:variables
}
